// Code generated by protoc-gen-go. DO NOT EDIT.
// source: example/example.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//@switcher struct HelloWorldDto
type HelloWorld struct {
	Field1               string   `protobuf:"bytes,1,opt,name=field1,proto3" json:"field1,omitempty"`
	Field2               string   `protobuf:"bytes,2,opt,name=field2,proto3" json:"field2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloWorld) Reset()         { *m = HelloWorld{} }
func (m *HelloWorld) String() string { return proto.CompactTextString(m) }
func (*HelloWorld) ProtoMessage()    {}
func (*HelloWorld) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c78cffa5d645ba4, []int{0}
}

func (m *HelloWorld) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloWorld.Unmarshal(m, b)
}
func (m *HelloWorld) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloWorld.Marshal(b, m, deterministic)
}
func (m *HelloWorld) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloWorld.Merge(m, src)
}
func (m *HelloWorld) XXX_Size() int {
	return xxx_messageInfo_HelloWorld.Size(m)
}
func (m *HelloWorld) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloWorld.DiscardUnknown(m)
}

var xxx_messageInfo_HelloWorld proto.InternalMessageInfo

func (m *HelloWorld) GetField1() string {
	if m != nil {
		return m.Field1
	}
	return ""
}

func (m *HelloWorld) GetField2() string {
	if m != nil {
		return m.Field2
	}
	return ""
}

type HelloWorld2 struct {
	Field2               string   `protobuf:"bytes,1,opt,name=field2,proto3" json:"field2,omitempty"`
	Field3               string   `protobuf:"bytes,2,opt,name=field3,proto3" json:"field3,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloWorld2) Reset()         { *m = HelloWorld2{} }
func (m *HelloWorld2) String() string { return proto.CompactTextString(m) }
func (*HelloWorld2) ProtoMessage()    {}
func (*HelloWorld2) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c78cffa5d645ba4, []int{1}
}

func (m *HelloWorld2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloWorld2.Unmarshal(m, b)
}
func (m *HelloWorld2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloWorld2.Marshal(b, m, deterministic)
}
func (m *HelloWorld2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloWorld2.Merge(m, src)
}
func (m *HelloWorld2) XXX_Size() int {
	return xxx_messageInfo_HelloWorld2.Size(m)
}
func (m *HelloWorld2) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloWorld2.DiscardUnknown(m)
}

var xxx_messageInfo_HelloWorld2 proto.InternalMessageInfo

func (m *HelloWorld2) GetField2() string {
	if m != nil {
		return m.Field2
	}
	return ""
}

func (m *HelloWorld2) GetField3() string {
	if m != nil {
		return m.Field3
	}
	return ""
}

//@switcher struct HelloWorldDtoResponseDto
type HelloWorldResponse struct {
	Field4               []string `protobuf:"bytes,1,rep,name=field4,proto3" json:"field4,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloWorldResponse) Reset()         { *m = HelloWorldResponse{} }
func (m *HelloWorldResponse) String() string { return proto.CompactTextString(m) }
func (*HelloWorldResponse) ProtoMessage()    {}
func (*HelloWorldResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c78cffa5d645ba4, []int{2}
}

func (m *HelloWorldResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloWorldResponse.Unmarshal(m, b)
}
func (m *HelloWorldResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloWorldResponse.Marshal(b, m, deterministic)
}
func (m *HelloWorldResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloWorldResponse.Merge(m, src)
}
func (m *HelloWorldResponse) XXX_Size() int {
	return xxx_messageInfo_HelloWorldResponse.Size(m)
}
func (m *HelloWorldResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloWorldResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HelloWorldResponse proto.InternalMessageInfo

func (m *HelloWorldResponse) GetField4() []string {
	if m != nil {
		return m.Field4
	}
	return nil
}

func init() {
	proto.RegisterType((*HelloWorld)(nil), "proto.HelloWorld")
	proto.RegisterType((*HelloWorld2)(nil), "proto.HelloWorld2")
	proto.RegisterType((*HelloWorldResponse)(nil), "proto.HelloWorldResponse")
}

func init() {
	proto.RegisterFile("example/example.proto", fileDescriptor_1c78cffa5d645ba4)
}

var fileDescriptor_1c78cffa5d645ba4 = []byte{
	// 132 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4d, 0xad, 0x48, 0xcc,
	0x2d, 0xc8, 0x49, 0xd5, 0x87, 0xd2, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0xac, 0x60, 0x4a,
	0xc9, 0x86, 0x8b, 0xcb, 0x23, 0x35, 0x27, 0x27, 0x3f, 0x3c, 0xbf, 0x28, 0x27, 0x45, 0x48, 0x8c,
	0x8b, 0x2d, 0x2d, 0x33, 0x35, 0x27, 0xc5, 0x50, 0x82, 0x51, 0x81, 0x51, 0x83, 0x33, 0x08, 0xca,
	0x83, 0x8b, 0x1b, 0x49, 0x30, 0x21, 0x89, 0x1b, 0x29, 0xd9, 0x72, 0x71, 0x23, 0x74, 0x1b, 0x21,
	0x29, 0x43, 0xd6, 0x8e, 0x10, 0x37, 0x46, 0xd1, 0x6e, 0xac, 0xa4, 0xc3, 0x25, 0x84, 0xd0, 0x1e,
	0x94, 0x5a, 0x5c, 0x90, 0x9f, 0x57, 0x9c, 0x0a, 0x57, 0x6d, 0x22, 0xc1, 0xa8, 0xc0, 0x0c, 0x57,
	0x6d, 0x92, 0xc4, 0x06, 0x76, 0xb1, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xe6, 0xd0, 0xdd, 0xae,
	0xd1, 0x00, 0x00, 0x00,
}
